# Generated by Django 6.0 on 2026-01-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationdelivery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_status_e1aed1_idx',
            old_name='notificatio_status_3cbf75_idx',
        ),
    ]
