# Generated by Django 6.0 on 2026-01-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_rename_notificatio_status_3cbf75_idx_notificatio_status_e1aed1_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["created_at"], name="notificati_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["status", "created_at"], name="notificati_status_created_at_idx"),
        ),
    ]

