# Generated by Django 5.2.9 on 2025-12-27 00:00

from __future__ import annotations

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="FrigateDetection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(db_index=True, default="frigate", max_length=32)),
                ("event_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("label", models.CharField(db_index=True, max_length=64)),
                ("camera", models.CharField(db_index=True, max_length=128)),
                ("zones", models.JSONField(blank=True, default=list)),
                ("confidence_pct", models.FloatField()),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("source_topic", models.CharField(blank=True, max_length=255)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["provider", "label", "-observed_at"],
                        name="frigate_det_provider_label_obs_idx",
                    ),
                    models.Index(
                        fields=["provider", "camera", "-observed_at"],
                        name="frigate_det_provider_camera_obs_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="frigatedetection",
            constraint=models.UniqueConstraint(
                fields=("provider", "event_id"),
                condition=~Q(event_id=""),
                name="frigate_detection_provider_event_id_unique_nonempty",
            ),
        ),
    ]
