# Generated by Django 5.2.9 on 2025-12-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_frigate', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='frigatedetection',
            new_name='integration_provide_7d67cf_idx',
            old_name='frigate_det_provider_label_obs_idx',
        ),
        migrations.RenameIndex(
            model_name='frigatedetection',
            new_name='integration_provide_f31721_idx',
            old_name='frigate_det_provider_camera_obs_idx',
        ),
    ]
