# Generated by Django 5.2.9 on 2025-12-28 00:00

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="ControlPanelDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                (
                    "integration_type",
                    models.CharField(choices=[("zwavejs", "Z-Wave JS"), ("home_assistant", "Home Assistant")], max_length=32),
                ),
                ("kind", models.CharField(choices=[("ring_keypad_v2", "Ring Keypad v2")], max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("external_key", models.CharField(max_length=200, unique=True)),
                ("external_id", models.JSONField(blank=True, default=dict)),
                ("action_map", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["integration_type"], name="control_pan_integra_8bd633_idx"),
                    models.Index(fields=["kind"], name="control_pan_kind_5a53ad_idx"),
                    models.Index(fields=["enabled"], name="control_pan_enable_9b3b75_idx"),
                ],
            },
        ),
    ]

