# Generated by Django 5.2.9 on 2025-12-29 00:00

from __future__ import annotations

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_panels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlpaneldevice",
            name="beep_volume",
            field=models.PositiveSmallIntegerField(
                default=50,
                validators=[MinValueValidator(1), MaxValueValidator(99)],
            ),
        ),
    ]

