# Generated by Django 5.2.9 on 2026-02-08 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locks", "0002_remove_door_lock_and_sync_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="doorcode",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("synced", "Synced")],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="doorcode",
            name="code_hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doorcode",
            name="pin_length",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
        migrations.AddField(
            model_name="doorcodelockassignment",
            name="slot_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doorcodelockassignment",
            name="sync_dismissed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="doorcodelockassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slot_index__isnull", False)),
                fields=("lock_entity_id", "slot_index"),
                name="door_code_lock_assignments_unique_lock_slot",
            ),
        ),
    ]

