# Generated by Django 6.0.2 on 2026-02-12 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='schedulertaskhealth',
            new_name='scheduler_s_task_na_f7effb_idx',
            old_name='scheduler_ta_task_na_99a1a7_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulertaskhealth',
            new_name='scheduler_s_instanc_3223fd_idx',
            old_name='scheduler_ta_instance_4d110a_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulertaskhealth',
            new_name='scheduler_s_task_na_1af27d_idx',
            old_name='scheduler_ta_task_na_e9b1bf_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulertaskhealth',
            new_name='scheduler_s_is_runn_b47b3f_idx',
            old_name='scheduler_ta_is_runn_05c2a6_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulertaskhealth',
            new_name='scheduler_s_consecu_4e17cd_idx',
            old_name='scheduler_ta_consec_51ed4b_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulertaskhealth',
            new_name='scheduler_s_updated_8e6cfb_idx',
            old_name='scheduler_ta_updated_8a1056_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulertaskrun',
            new_name='scheduler_s_task_na_10dffc_idx',
            old_name='scheduler_ta_task_na_4f5f1e_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulertaskrun',
            new_name='scheduler_s_instanc_fd4b83_idx',
            old_name='scheduler_ta_instance_312a86_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulertaskrun',
            new_name='scheduler_s_status_ab7443_idx',
            old_name='scheduler_ta_status_6aa9ca_idx',
        ),
    ]
