# Generated by Django 6.0 on 2026-01-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0011_ruleruntimestate_failure_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmevent',
            name='event_type',
            field=models.CharField(choices=[('armed', 'Armed'), ('disarmed', 'Disarmed'), ('pending', 'Pending'), ('triggered', 'Triggered'), ('code_used', 'Code used'), ('sensor_triggered', 'Sensor triggered'), ('failed_code', 'Failed code'), ('state_changed', 'State changed'), ('integration_offline', 'Integration offline'), ('integration_recovered', 'Integration recovered')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ruleruntimestate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('satisfied', 'Satisfied'), ('cooldown', 'Cooldown'), ('error_suspended', 'Error Suspended')], default='pending', max_length=32),
        ),
        migrations.AddIndex(
            model_name='ruleruntimestate',
            index=models.Index(fields=['error_suspended'], name='alarm_ruler_error_s_187cde_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleruntimestate',
            index=models.Index(fields=['next_allowed_at'], name='alarm_ruler_next_al_b679cc_idx'),
        ),
    ]
