# Generated by Django 6.0.5 on 2026-05-12 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0018_drop_global_timing_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_index', models.IntegerField(help_text="Position of the action in the rule's definition.then list")),
                ('action_payload', models.JSONField(help_text='Immutable snapshot of the action JSON at enqueue time')),
                ('delay_seconds', models.IntegerField()),
                ('scheduled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fire_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('fired', 'Fired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='scheduled', max_length=16)),
                ('cancel_reason', models.CharField(blank=True, choices=[('disarm', 'Alarm disarmed'), ('manual', 'Manual operator cancel'), ('rule_deleted', 'Rule was deleted or disabled'), ('stale_after_restart', 'Backend was down past the stale threshold')], default='', max_length=32)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('fire_result', models.JSONField(blank=True, help_text='What the handler returned (success result, error message, etc.)', null=True)),
                ('armed_state_at_schedule', models.CharField(choices=[('disarmed', 'Disarmed'), ('arming', 'Arming'), ('armed_home', 'Armed home'), ('armed_away', 'Armed away'), ('armed_night', 'Armed night'), ('armed_vacation', 'Armed vacation'), ('pending', 'Pending'), ('triggered', 'Triggered')], help_text='Alarm state at enqueue time; used to scope disarm cancellation', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_actions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='alarm.rule')),
            ],
            options={
                'ordering': ['-fire_at', '-id'],
                'indexes': [models.Index(fields=['status', 'fire_at'], name='alarm_pendi_status_1573ef_idx'), models.Index(fields=['rule', 'status'], name='alarm_pendi_rule_id_a03794_idx')],
            },
        ),
    ]
