# Generated by Django 6.0.5 on 2026-06-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0019_pendingaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmCodeLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
