# Generated by Django 6.0.6 on 2026-07-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0020_repair_stale_rule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
